---
title: "Test Analysis Report"
author: 
  - name: "First Author"
    affiliation: "NIBSC"
    email: "first.author@nibsc.org"
  - name: "Second Author"
    affiliation: "NIBSC"
    email: "second.author@nibsc.org"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: nibscdoc::report_html
editor_options:
  chunk_output_type: console
---


```{r, echo=FALSE, message=FALSE, error=FALSE, warning=FALSE}
library(knitr)
library(ggplot2)
```

# Introduction

This is intended to be a test, to verify the rendering function works as it should.

# Results

```{r}
data(diamonds)
```


## Analysis 1


```{r, fig.cap="Diamonds price and carats. Relationship between the price of diamonds and their evaluated carats"}
ggplot2::ggplot(diamonds, aes(x=carat, y=price, fill=color, color=color))+
  ggplot2::geom_point()+
  ggplot2::geom_smooth()
```


## Analysis 2




```{r, fig.cap="Diamonds price and carats. Relationship between the price of diamonds and the carat depending on the quality of the cut"}
ggplot2::ggplot(diamonds, aes(x=carat, y=price, color=cut))+
  ggplot2::geom_point()+
  ggplot2::geom_smooth()
```




# QC

This is just a test, nothing to be shown here.

# Materials and Methods

This is just a test, nothing to be shown here.
Data use available datasets as part of the *ggplot2* package.
